// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace ConsoleRunner
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "RichEnumGenerator", "1.0.0.0" )]
    public sealed partial class Animal
    {
        private readonly System.String _size;
        private readonly System.Int32 _number;

        public static readonly Animal Dog = new Animal(
            size: "Small", 	
            number: 0	
        );
        public static readonly Animal Cat = new Animal(
            size: "Small", 	
            number: 1	
        );
        public static readonly Animal Horse = new Animal(
            size: "Large", 	
            number: 2	
        );

        private Animal(
            System.String size, 	
            System.Int32 number	
        )
        {
            _size = size;	
            _number = number;	
        }

		/// <summary>
		/// Returns all the enumeration values.
		/// </summary>
		public static System.Collections.Generic.IEnumerable<Animal> GetValues()
		{
			yield return Dog;
			yield return Cat;
			yield return Horse;
		}
    }
}
