// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace ConsoleRunner
{
	public sealed partial class Animal
	{
		private readonly System.String _size;
		private readonly System.Int32 _number;

		public static readonly Animal Dog = new Animal(
				size: "Small", 	
				number: 0	
		);
		public static readonly Animal Cat = new Animal(
				size: "Small", 	
				number: 1	
		);
		public static readonly Animal Horse = new Animal(
				size: "Large", 	
				number: 2	
		);

		private Animal(
			System.String size, 	
			System.Int32 number	
		)
		{
			_size = size;	
			_number = number;	
		}
	}
}
