// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

using System;

namespace ConsoleRunner
{
	public sealed partial class Animal
	{
		public static readonly Animal Dog = new Animal(
		);
		public static readonly Animal Cat = new Animal(
		);
		public static readonly Animal Horse = new Animal(
		);

		private Animal()
		{
		}
	}
}
